/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManajemenInventaris;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Login_Pengembalian_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Login_Pengembalian_Panel
     */
    private Manajemen_Main parent = null;
    
    public Login_Pengembalian_Panel(Manajemen_Main parent) {
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_pengembalian = new javax.swing.JButton();
        text_pengembalian = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        btn_pengembalian.setText("jButton1");
        btn_pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pengembalianActionPerformed(evt);
            }
        });

        text_pengembalian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_pengembalianKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_pengembalian)
                    .addComponent(text_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1026, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(text_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_pengembalian)
                .addContainerGap(357, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pengembalianActionPerformed
        // TODO add your handling code here:
        
         try{
            String sql = "SELECT * FROM tbl_murid WHERE nis = '" + text_pengembalian.getText()+ "'";
            java.sql.Connection conn = DBConnection.getKoneksi();
            java.sql.Statement stm = conn.createStatement();    
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            if (res.next()) {
                if (res.getString("level").equals("1")) {
                   parent.pengembalianBarangPanel = new Manajemen_PengembalianBarangPanel(parent);
                   parent.add(parent.pengembalianBarangPanel);
                   this.revalidate();
                   parent.revalidate();
                   parent.login_Pengembalian_Panel.setVisible(false);
                    
                    
                }
            }
            else {
                JOptionPane.showMessageDialog(null,"Maaf Data Tidak Valid");
            }
        }catch(Exception e){
            e.getMessage();
        }
        text_pengembalian.setText("");
    }//GEN-LAST:event_btn_pengembalianActionPerformed

    private void text_pengembalianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_pengembalianKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
              try{
            String sql = "SELECT * FROM tbl_murid WHERE nis = '" + text_pengembalian.getText()+ "'";
            java.sql.Connection conn = DBConnection.getKoneksi();
            java.sql.Statement stm = conn.createStatement();    
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            if (res.next()) {
                if (res.getString("id_level").equals("1")) {
                   parent.pengembalianBarangPanel = new Manajemen_PengembalianBarangPanel(parent);
                   parent.add(parent.pengembalianBarangPanel);
                   this.revalidate();
                   parent.revalidate();
                   parent.login_Pengembalian_Panel.setVisible(false);
                    
                    
                }
            }
            else {
                JOptionPane.showMessageDialog(null,"Maaf Data Tidak Valid");
            }
        }catch(Exception e){
            e.getMessage();
        }
        text_pengembalian.setText("");  
        }
    }//GEN-LAST:event_text_pengembalianKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_pengembalian;
    private javax.swing.JTextField text_pengembalian;
    // End of variables declaration//GEN-END:variables
}
